env: "local"

http_server:
  address: "localhost:3050"
  timeout: 4s
  idle_timeout: 60s

pg:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "root"
  db_name: "test_golang"
  ssl_mode: "disable"

mongo:
  username: mongo-admin
  password: passw0rd
  host: localhost
  port: 27017
  db_name: auth_service

token:
  accessTokenTTL: 15m
  refreshTokenTTL: 14400m
  privateKey: W{GONsdjk

